---
title: "Logging on to Aire"
format: 
  html: 
    html-math-method: katex
  pdf: 
    geometry: 
      - top=30mm
      - left=20mm
  docx: default
---

In order to log in to the Aire HPC platform, you need an Aire account. This is separate from your ARC account. 

When you access Aire for the first time, you will have to change your OTP to a secure password of your choosing.

# Routes to access Aire

Aire can be accessed remotely via the rash gateway, or can be connected to via a machine on campus (on the University network).

## Remote access via rash

Aire can be accessed via the rash system (please see the [knowledge base article on remote ssh access via rash](https://it.leeds.ac.uk/it?id=kb_article&sys_id=e787b3561bd34ad4ba670ed0f54bcb17&spa=1) for information on using rash):

```bash
ssh username@login1.aire.leeds.ac.uk -J username@rash.leeds.ac.uk
```

replacing `username` with the Aire account username provided to you by the Research Computing team.

## Access via a University machine

Aire can also be access via a machine on campus. For example, if logged on to ARC 4, you can then use:

```bash
ssh username@login1.aire.leeds.ac.uk
```

# First time log on password configuration

When you first log on to Aire, you will need to use your OTP and immediately set a new password.

1. Connect via ssh to `login1.aire.leeds.ac.uk`
2. Enter your Aire username and OTP
3. On your first successful login, you will be asked to change your password, and will be prompted to confirm your current password. Enter your OTP provided by Research Computing again.
4. Type in a new secure password when prompted.
5. Confirm this new password by typing it in again.

You will now be logged out of Aire. You can log in again, this time using your new provate password.


Please see the [knowledge base article on remote ssh access via rash](https://it.leeds.ac.uk/it?id=kb_article&sys_id=e787b3561bd34ad4ba670ed0f54bcb17&spa=1) to learn more about configuring your ssh connections, such as increasing the automatic time-out time etc.